apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: nodejs-website
build:
  artifacts:
  - image: node-web
    context: backend
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yml
